global:
  scrape_interval: 30s
  scrape_timeout: 10s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: services
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - 'host.docker.internal:8143'
          - 'host.docker.internal:8144'