server:
  port: 8143
  servlet:
    context-path: /

logging:
  level:
    root: INFO

spring:
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
      temp:
        use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    platform: postgresql
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_URL:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:pmrodrigues}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  liquibase:
    change-log: classpath:/db/changelog/changelog.xml
    enabled: true
    test-rollback-on-update: false
    url: jdbc:postgresql://${POSTGRES_URL:localhost:5432}/${POSTGRES_DB:pmrodrigues}
    user: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${KEYCLOAK_CLIENT_ID:94cf4fee-1b57-4e3c-8d97-195e7f7f1173}
            client-secret: ${KEYCLOAK_CLIENT_SECRET:gNjirmWqaUiP4NWREgRDpbzJpnq7WSZD}
            scope: openid
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            issuerUri: http://${KEYCLOAK_LOCATION:localhost:8080}/auth/realms/master
feign:
  encoder:
    charset-from-content-type: true
  autoconfiguration:
    jackson:
      enabled: true
  metrics:
    enabled: true

keycloak:
  auth-server-url: http://${KEYCLOAK_LOCATION:localhost:8080}/auth/
  realm: ${KEYCLOAK_REALM:master}
  resource: 94cf4fee-1b57-4e3c-8d97-195e7f7f1173
  credentials:
    secret: gNjirmWqaUiP4NWREgRDpbzJpnq7WSZD
  ssl-required: none
  bearer-only: true
  principal-attribute: preferred_username
  public-client: true
  confidential-port: 0

client:
  email:
    location: ${CLIENT_EMAIL_LOCATION:localhost:8144}
  user:
    location: ${KEYCLOAK_LOCATION:localhost:8080}

management:
  server:
    port: 1491
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      simple:
        enabled=true:
  endpoints:
    web:
      exposure:
        include: '*'
