apiVersion: v1
kind: Pod
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  containers:
    - name: keycloak
      image: quay.io/keycloak/keycloak:legacy
      ports:
        - containerPort: 8080
        - containerPort: 8443
      env:
        - name: DB_VENDOR
          value: POSTGRES
        - name: DB_ADDR
          valueFrom:
            configMapKeyRef:
              name: postgres-configmap
              key: POSTGRES_URL
        - name: DB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: postgres-configmap
              key: POSTGRES_DB
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: postgres-configmap
              key: POSTGRES_USER
        - name: DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: postgres-configmap
              key: POSTGRES_PASSWORD
        - name: KEYCLOAK_USER
          value: admin
        - name: KEYCLOAK_PASSWORD
          value: admin
      resources:
        limits:
          memory: 256Mi
          cpu: "1"