apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  containers:
    - name: postgres
      image: postgres:14.6-bullseye
      ports:
        - containerPort: 5432
      envFrom:
        - configMapRef:
            name: postgres-configmap
      resources:
        limits:
          memory: 512Mi
          cpu: "1"