apiVersion: v1
kind: Service
metadata:
  name: user-schema
spec:
  type: NodePort
  selector:
    app: user-schema
  ports:
    - name: user-schema
      port: 8143
    - name: monitoring-user-schema
      port: 1491

