server:
  port: 8144
  servlet:
    context-path: /

logging:
  level:
    root: INFO
    app: DEBUG
  group:
    app:
      - com.pmrodrigues

spring:
  output:
    ansi:
      enabled: DETECT
  kafka:
    bootstrapAddress: ${KAFKA_BOOTSTRAP_URL:localhost:29092}
  mail:
    host: localhost
    port: 25
    protocol: smtp
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${KEYCLOAK_CLIENT_ID:4c815705-49c8-43cc-88e7-eb1e9b8fe253}
            client-secret: ${KEYCLOAK_CLIENT_SECRET:N1v6yxmH05767mtUmx8o3fXpF6v7tBb3}
            scope: openid
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            issuerUri: http://${KEYCLOAK_LOCATION:localhost:8080}/auth/realms/master

keycloak:
  auth-server-url: http://${KEYCLOAK_LOCATION:localhost:8080}/auth/
  realm: master
  resource: 4c815705-49c8-43cc-88e7-eb1e9b8fe253
  credentials:
    secret: N1v6yxmH05767mtUmx8o3fXpF6v7tBb3
  ssl-required: none
  bearer-only: true
  principal-attribute: preferred_username
  public-client: true
  confidential-port: 0

emails:
  templates:
    - newUser:
        from: new-user@email.com
        subject: Welcome {0}!
        message: teste {0}
        type: text/plain

feign:
  encoder:
    charset-from-content-type: true
  autoconfiguration:
    jackson:
      enabled=true:

management:
  server:
    port: 1492
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      simple:
        enabled=true:
      prometheus:
        pushgateway:
          enabled: true
          base-url: http://localhost:9091
          shutdown-operation: push
  endpoints:
    web:
      exposure:
        include: '*'