name: PMRodrigues Project Setup

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Compose
      run: |
        sudo docker-compose -f infrastructure/docker-compose.yaml up -d
      working-directory: .

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '18'

    - name: Build with Maven
      run: mvn clean package jacoco:report -Dmaven.test.failure.ignore=true
      working-directory: .

    - name: Test Report
      uses: mikepenz/action-junit-report@v4
      if: success() || failure()
      with:
        report_paths: '**/target/surefire-reports/TEST-*.xml'
        detailed_summary: true
        include_passed: true

    - name: Add coverage to PR
      uses: madrapps/jacoco-report@v1.6.1
      with:
        paths: '**/target/site/jacoco-resources/jacoco.xml'
        token: ${{ secrets.GITHUB_TOKEN }}
        min-coverage-overall: 40
        min-coverage-changed-files: 60
        title: '# :lobster: Coverage Report'
        pass-emoji: ':green_circle:'
        fail-emoji: ':red_circle:'


    - name: Stop Docker Compose
      if: success() || failure()
      run: |
        sudo docker-compose -f infrastructure/docker-compose.yaml down
      working-directory: .

    - name: Clean up Docker
      if: success() || failure()
      run: |
        docker system prune -af
