name: Preparing PMRodrigues Projects
on: push
jobs:
  test:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v2
        with:
          compose-file: "./infrastructure/docker-compose.yaml"
      - name: Build the stack      
        run: docker-compose up -d
